### ISSUE TITLE
[md-select] Not opening again after closing.

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-web#4915]
**Reproduction steps**

- Click on the select element (to open the options)
- Click on the select element *again* (not an option)
- Click a third time on the select element trying to reopen the options, **It fails to open**

You can use this playground to test the steps : https://lit.dev/playground/#gist=a088478f44ed5f05649cd0ca20820173

**Version**

`v1.0.0-pre.17`

**Comment by VandeurenGlenn** [comment]
Ah it opens for ya? It didn't open for a while now, how you opening it?

**Comment by e111077** [comment]
This is fixed in #4907. awaiting release on the 25th

**Comment by vdegenne** [comment]
@e111077 Does it get rid of this problem https://github.com/material-components/material-web/pull/4770 ? Or are the tests still failing for this PR?

**Comment by e111077** [comment]
investigated looks unrelated. Will comment in that PR
